# Generated by Django 5.0 on 2023-12-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='otp_status',
            field=models.CharField(choices=[('Yes', 'OTP YES'), ('Yes', 'OTP NO')], default='yes', max_length=100),
        ),
    ]
