# Generated by Django 5.0 on 2023-12-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_myuser_otp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='otp_status',
            field=models.CharField(choices=[('Yes', 'LOGIN OTP YES'), ('Yes', 'LOGIN OTP NO')], default='yes', max_length=100),
        ),
    ]
