# Generated by Django 5.0 on 2023-12-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_myuser_otp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='currency',
            field=models.CharField(choices=[('$', 'Dollar'), ('€', 'Euro'), ('£', 'British Pounds'), ('£', 'Japanese Yen'), ('£', 'Indian Rupee')], max_length=4),
        ),
    ]
