# Generated by Django 5.0 on 2023-12-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userbankaccount_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccounttype',
            name='miniimum_withdraw',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
        ),
    ]
