# Generated by Django 5.0 on 2023-12-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_bankaccounttype_miniimum_withdraw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccounttype',
            old_name='miniimum_withdraw',
            new_name='minimum_withdraw',
        ),
    ]
