# Generated by Django 5.0 on 2023-12-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_miniimum_withdraw_bankaccounttype_minimum_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='otp_status',
            field=models.CharField(choices=[('LOGIN OTP YES', 'LOGIN OTP YES'), ('LOGIN OTP NO', 'LOGIN OTP NO')], default='LOGIN OTP YES', max_length=100),
        ),
    ]
