# Generated by Django 5.0 on 2023-12-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_myuser_otp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
