# Generated by Django 5.0 on 2023-12-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_myuser_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
