# Generated by Django 5.0 on 2025-02-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='currency',
            field=models.CharField(choices=[('$', 'Dollar'), ('€', 'Euro'), ('£', 'British Pounds'), ('JPY', 'Japanese Yen'), ('INR', 'Indian Rupee'), ('₩', 'Korean Won KRW')], max_length=4),
        ),
    ]
