# Generated by Django 5.0 on 2025-02-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='beneficiary_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='iban_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='route_code',
            field=models.CharField(max_length=100),
        ),
    ]
